spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/ziggs_db
    username: ziggs
    password: ziggs
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

